sonar.projectKey=cw-isplit-backend
sonar.projectName=Coding Works iSplit Backend
sonar.sources=src
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.exclusions=node_modules/**,build/**,logs/**,scripts/**,deploy.ps1,**/*.spec.ts,**/*.test.ts,.vscode/**